### ISSUE TITLE
Think about what this should / could be

### ISSUE THREAD

**Issue by gaborcsardi** [MangoTheCat/tracer#1]
1. Something called automatically after an error, via `options(error = tracer)`
2. Something instead of `traceback()`

Potentially both?

**Comment by gaborcsardi** [comment]
Also, the stack trace from `recover()` could use this... not sure how, though.

Or we can supply a new replacement of `recover()`.

**Comment by krlmlr** [comment]
+1 for a new recover() replacement. The base version lacks an argument to specify the number of calls to be skipped. Use case: An "interrupt mode" for testthat where a failure/error launches the debugger at the precise location of the failure.

The ["bettertrace" package](https://github.com/robertzk/bettertrace) installs the handler in .onLoad().

**Comment by gaborcsardi** [comment]
OK, so here is a plan. We will have the following functions (with probably different names):
- [x] `traceback`: a `base::traceback` replacement.
- [x] `tracer`: a hook that can be set via `options(error = tracer)`, and shows a nice trace after an error.
- [x] `recover`: a replacement for `recover`, this is for later.

**Comment by gaborcsardi** [comment]
And of course, even the first one requires our own `options(error= ...)` replacement, to dump more data than the default....
