### ISSUE TITLE
Make bt do something different

### ISSUE THREAD

**Issue by richierocks** [MangoTheCat/tracer#6]
I don't quite get why `bt` is an alias for `tb`.  It feels like it ought to do a traceback with a different set of defaults.

Perhaps have one function show the call stack top to bottom, and the other one show the call stack from bottom to top?

**Comment by gaborcsardi** [comment]
It might be just me, but sometimes I type `bt`, sometimes `tb`.  It's because in some debuggers, e.g. gdb, it is `bt`. So it is just a convenience "feature".

**Comment by gaborcsardi** [comment]
If you think it is very bad, maybe I can remove `bt` from the package, and just set up an alias for myself.
