### ISSUE TITLE
Turn-off coloring/styling

### ISSUE THREAD

**Issue by mbojan** [MangoTheCat/tracer#7]
Awesome!

However, is it possible to turn off the styling/coloring with e.g. an `option()`? Perhaps a "plain" style can be implemented? It conflicts with other coloring package I'm using (same for `clisymbols` for that matter...).

**Comment by gaborcsardi** [comment]
Thanks!

``` r
options(crayon.enabled = FALSE)
```

turns off the colors. 

I am not sure what you mean by `clisymbols`. What's wrong with that?

**Comment by jimhester** [comment]
While we are here, you might want to restrict the default color scheme to ANSI 16. The extended colors used as defaults are unappealing with my color scheme for instance. I see this is configurable though so 👍  for that!

![screenshot 2016-11-18 14 54 03](https://cloud.githubusercontent.com/assets/205275/20444407/f68f5ef0-ad9e-11e6-9f66-43b3b45412e9.png)

**Comment by gaborcsardi** [comment]
Yeah, that does look bad. If you send me a good 16-color color map, I can make that the default, except `crayon` detects 256 colors. :)

**Comment by mbojan** [comment]
Thumbs up. I use bright Solarized  too :)

**Comment by gaborcsardi** [comment]
@mbojan So, what is wrong with `clisymbols`? I guess I can add an option to turn them off, if support for them is not detected correctly....

**Comment by mbojan** [comment]
@gaborcsardi I think its OK with `clisymbols`. I had a first impression that using `colorout` is breaking that too:

``` r
> lm("a")
Error in eval(expr, envir, enclos) : object 'a' not found
> tb()

  1 [38;5;244mstats::[38;5;184mlm [38;5;251m("a") 
  2 [38;5;244mbase::[38;5;184meval [38;5;251m(mf, parent.frame()) 
  3 [38;5;184meval [38;5;251m(expr, envir, enclos) 
  4 [38;5;244mstats::[38;5;184m<anonymous> [38;5;251m(formula = "a", drop.unused.levels = TRUE) 
  5 [38;5;244mstats::[38;5;184mmodel.frame.default [38;5;251m(formula = "a", drop.unused.levels = TRUE) 
  6 [38;5;244mstats::[38;5;184mas.formula [38;5;251m(formula) 
  7 [38;5;244mstats::[38;5;184mformula [38;5;251m(object, env = baseenv()) 
  8 [38;5;244mstats::[38;5;184mformula.character [38;5;251m(object, env = baseenv()) 
  9 [38;5;244mstats::[38;5;184mformula [38;5;251m(eval(parse(text = x, keep.source = FALSE)[[1L]])) 
 10 [38;5;244mbase::[38;5;184meval [38;5;251m(parse(text = x, keep.source = FALSE)[[1L]]) 
 11 [38;5;184meval [38;5;251m(expr, envir, enclos) 

[38;5;203m ✖ Error in eval(expr, envir, enclos) : object 'a' not found
> tb(1)
Cannot show calls from top level
> tb(2)

    9     m <- match(c("formula", "data", "subset", "weights", "na.action", 
   10         "offset"), names(mf), 0L)
   11     mf <- mf[c(1L, m)]
   12     mf$drop.unused.levels <- TRUE
   13     mf[[1L]] <- quote(stats::model.frame)
[48;5;203m ❯ 14     mf <- eval(mf, parent.frame())
   15     if (method == "model.frame") 
   16         return(mf)
   17     else if (method != "qr") 
   18         warning(gettextf("method = '%s' is not supported. Using 'qr'", 
   19             method), domain = NA)

   [38;5;244mstats::[38;5;184mlm (?), function without source

> 
```

When I turn-off crayon I can see more easily that the symbols appear correctly
